# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vikash/projects/assertc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vikash/projects/assertc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikash/projects/assertc/CMakeFiles /home/vikash/projects/assertc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vikash/projects/assertc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assertc

# Build rule for target.
assertc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assertc
.PHONY : assertc

# fast build rule for target.
assertc/fast:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/build
.PHONY : assertc/fast

src/assertc.o: src/assertc.c.o

.PHONY : src/assertc.o

# target to build an object file
src/assertc.c.o:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/assertc.c.o
.PHONY : src/assertc.c.o

src/assertc.i: src/assertc.c.i

.PHONY : src/assertc.i

# target to preprocess a source file
src/assertc.c.i:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/assertc.c.i
.PHONY : src/assertc.c.i

src/assertc.s: src/assertc.c.s

.PHONY : src/assertc.s

# target to generate assembly for a file
src/assertc.c.s:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/assertc.c.s
.PHONY : src/assertc.c.s

src/collection.o: src/collection.c.o

.PHONY : src/collection.o

# target to build an object file
src/collection.c.o:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/collection.c.o
.PHONY : src/collection.c.o

src/collection.i: src/collection.c.i

.PHONY : src/collection.i

# target to preprocess a source file
src/collection.c.i:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/collection.c.i
.PHONY : src/collection.c.i

src/collection.s: src/collection.c.s

.PHONY : src/collection.s

# target to generate assembly for a file
src/collection.c.s:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/collection.c.s
.PHONY : src/collection.c.s

src/reporters/spec.o: src/reporters/spec.c.o

.PHONY : src/reporters/spec.o

# target to build an object file
src/reporters/spec.c.o:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/reporters/spec.c.o
.PHONY : src/reporters/spec.c.o

src/reporters/spec.i: src/reporters/spec.c.i

.PHONY : src/reporters/spec.i

# target to preprocess a source file
src/reporters/spec.c.i:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/reporters/spec.c.i
.PHONY : src/reporters/spec.c.i

src/reporters/spec.s: src/reporters/spec.c.s

.PHONY : src/reporters/spec.s

# target to generate assembly for a file
src/reporters/spec.c.s:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/reporters/spec.c.s
.PHONY : src/reporters/spec.c.s

src/runner.o: src/runner.c.o

.PHONY : src/runner.o

# target to build an object file
src/runner.c.o:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/runner.c.o
.PHONY : src/runner.c.o

src/runner.i: src/runner.c.i

.PHONY : src/runner.i

# target to preprocess a source file
src/runner.c.i:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/runner.c.i
.PHONY : src/runner.c.i

src/runner.s: src/runner.c.s

.PHONY : src/runner.s

# target to generate assembly for a file
src/runner.c.s:
	$(MAKE) -f CMakeFiles/assertc.dir/build.make CMakeFiles/assertc.dir/src/runner.c.s
.PHONY : src/runner.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... assertc"
	@echo "... edit_cache"
	@echo "... src/assertc.o"
	@echo "... src/assertc.i"
	@echo "... src/assertc.s"
	@echo "... src/collection.o"
	@echo "... src/collection.i"
	@echo "... src/collection.s"
	@echo "... src/reporters/spec.o"
	@echo "... src/reporters/spec.i"
	@echo "... src/reporters/spec.s"
	@echo "... src/runner.o"
	@echo "... src/runner.i"
	@echo "... src/runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

